// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/account/password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/password">> = Specific
  const handler = {} as typeof import("../../src/app/account/password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/profile">> = Specific
  const handler = {} as typeof import("../../src/app/account/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ao-vivo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ao-vivo">> = Specific
  const handler = {} as typeof import("../../src/app/ao-vivo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ebasketball/[league]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ebasketball/[league]">> = Specific
  const handler = {} as typeof import("../../src/app/ebasketball/[league]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/esoccer/[league]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/esoccer/[league]">> = Specific
  const handler = {} as typeof import("../../src/app/esoccer/[league]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/esoccer/gt-league/disparidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/esoccer/gt-league/disparidade">> = Specific
  const handler = {} as typeof import("../../src/app/esoccer/gt-league/disparidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/esoccer/gt-league/metodos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/esoccer/gt-league/metodos">> = Specific
  const handler = {} as typeof import("../../src/app/esoccer/gt-league/metodos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/esoccer/gt-league/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/esoccer/gt-league">> = Specific
  const handler = {} as typeof import("../../src/app/esoccer/gt-league/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/esoccer/gt-league/panorama/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/esoccer/gt-league/panorama">> = Specific
  const handler = {} as typeof import("../../src/app/esoccer/gt-league/panorama/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/esoccer/gt-league/raio-x/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/esoccer/gt-league/raio-x">> = Specific
  const handler = {} as typeof import("../../src/app/esoccer/gt-league/raio-x/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inicio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inicio">> = Specific
  const handler = {} as typeof import("../../src/app/inicio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/methods">> = Specific
  const handler = {} as typeof import("../../src/app/methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/security/logins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security/logins">> = Specific
  const handler = {} as typeof import("../../src/app/security/logins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ao-vivo/signals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ao-vivo/signals">> = Specific
  const handler = {} as typeof import("../../src/app/api/ao-vivo/signals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/disparidade/gt-options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/disparidade/gt-options">> = Specific
  const handler = {} as typeof import("../../src/app/api/disparidade/gt-options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/disparidade/gt-pair/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/disparidade/gt-pair">> = Specific
  const handler = {} as typeof import("../../src/app/api/disparidade/gt-pair/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/disparidade/gt-xray/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/disparidade/gt-xray">> = Specific
  const handler = {} as typeof import("../../src/app/api/disparidade/gt-xray/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gt-league/live-table/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gt-league/live-table">> = Specific
  const handler = {} as typeof import("../../src/app/api/gt-league/live-table/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gt-league/metodos/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gt-league/metodos/refresh">> = Specific
  const handler = {} as typeof import("../../src/app/api/gt-league/metodos/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gt-league/panorama/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gt-league/panorama">> = Specific
  const handler = {} as typeof import("../../src/app/api/gt-league/panorama/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
