CREATE TABLE IF NOT EXISTS `alert_method_rules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  `transport_channel` VARCHAR(16) NOT NULL DEFAULT 'webhook',
  `league_type` VARCHAR(32) NOT NULL,
  `method_code` VARCHAR(16) NOT NULL,
  `series` VARCHAR(1) DEFAULT NULL,
  `player_name` VARCHAR(120) DEFAULT NULL,
  `apx_min` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `min_occurrences` INT UNSIGNED NOT NULL DEFAULT 1,
  `window_days` SMALLINT UNSIGNED NOT NULL DEFAULT 30,
  `recipients` TEXT NOT NULL,
  `webhook_url` VARCHAR(500) DEFAULT NULL,
  `note` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_evaluated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_alert_rules_active_method` (`is_active`, `league_type`, `method_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `alert_method_dispatches` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rule_id` BIGINT UNSIGNED NOT NULL,
  `signal_key` VARCHAR(255) NOT NULL,
  `confrontation_key` VARCHAR(255) NOT NULL,
  `confrontation_label` VARCHAR(255) NOT NULL,
  `day_key` VARCHAR(10) NOT NULL,
  `occurrence_match_id` VARCHAR(64) NOT NULL,
  `occurrence_played_at` DATETIME NOT NULL,
  `apx` DECIMAL(5,2) NOT NULL,
  `total_occurrences` INT UNSIGNED NOT NULL,
  `payload_text` LONGTEXT NOT NULL,
  `recipients_snapshot` TEXT NOT NULL,
  `transport_status` VARCHAR(20) NOT NULL,
  `transport_response` LONGTEXT DEFAULT NULL,
  `sent_at` DATETIME DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_alert_dispatch_rule_signal` (`rule_id`, `signal_key`),
  INDEX `idx_alert_dispatch_rule_created` (`rule_id`, `created_at`),
  INDEX `idx_alert_dispatch_status_created` (`transport_status`, `created_at`),
  CONSTRAINT `fk_dispatch_rule` FOREIGN KEY (`rule_id`) REFERENCES `alert_method_rules` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
