CREATE TABLE IF NOT EXISTS portal_method_catalog (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  league_type VARCHAR(32) NOT NULL,
  code VARCHAR(32) NOT NULL,
  label VARCHAR(64) NOT NULL,
  family VARCHAR(24) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sync_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_portal_method_catalog_league_code (league_type, code),
  KEY idx_portal_method_catalog_league_status (league_type, status, sort_order)
);

CREATE TABLE IF NOT EXISTS portal_method_occurrences (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  league_type VARCHAR(32) NOT NULL,
  series VARCHAR(1) NULL,
  method_code VARCHAR(32) NOT NULL,
  player_name VARCHAR(120) NOT NULL,
  opponent_name VARCHAR(120) NOT NULL,
  confrontation_key VARCHAR(255) NOT NULL,
  confrontation_label VARCHAR(255) NOT NULL,
  occurrence_match_id VARCHAR(64) NOT NULL,
  occurrence_played_at DATETIME NOT NULL,
  day_key VARCHAR(10) NOT NULL,
  day_label VARCHAR(10) NOT NULL,
  window_label VARCHAR(24) NOT NULL,
  season_id INT NULL,
  result VARCHAR(1) NOT NULL,
  full_time_score VARCHAR(16) NOT NULL,
  wins INT UNSIGNED NOT NULL,
  draws INT UNSIGNED NOT NULL,
  losses INT UNSIGNED NOT NULL,
  apx DECIMAL(5,2) NOT NULL,
  total_occurrences INT UNSIGNED NOT NULL,
  trigger_sequence_json LONGTEXT NULL,
  day_sequence_json LONGTEXT NULL,
  day_history_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  synced_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_portal_method_occurrence_unique (league_type, method_code, confrontation_key, occurrence_match_id),
  KEY idx_portal_method_occurrence_league_played (league_type, occurrence_played_at),
  KEY idx_portal_method_occurrence_league_series_played (league_type, series, occurrence_played_at),
  KEY idx_portal_method_occurrence_league_method_played (league_type, method_code, occurrence_played_at)
);

CREATE TABLE IF NOT EXISTS portal_method_sync_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  league_type VARCHAR(32) NOT NULL,
  method_code VARCHAR(32) NOT NULL,
  window_days SMALLINT UNSIGNED NOT NULL,
  status VARCHAR(16) NOT NULL,
  started_at DATETIME NOT NULL,
  finished_at DATETIME NULL,
  upserted_count INT UNSIGNED NOT NULL DEFAULT 0,
  removed_count INT UNSIGNED NOT NULL DEFAULT 0,
  skipped_count INT UNSIGNED NOT NULL DEFAULT 0,
  error_message LONGTEXT NULL,
  details_json LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_portal_method_sync_runs_lookup (league_type, method_code, started_at),
  KEY idx_portal_method_sync_runs_status (status, started_at)
);
